name: Build & Publish to TestPyPI

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Upload to PyPi-Test?"
        required: true
        default: "true"
        type: choice
        options:
          - "true"
          - "false"

jobs:
  build_wheels:
    # We'll build on a matrix of OSes and Python versions.
    runs-on: windows-2019
    env:
      CIBW_BUILD: "cp39-* cp310-* cp311-* cp312-*"
      CIBW_SDIST: "true"

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          pip install --upgrade pip && pip install cibuildwheel twine

      - name: Build wheels
        run: cibuildwheel --platform windows --output-dir dist

      - name: Upload to Test PyPI
        run: |
            twine upload --repository testpypi dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_PASSWORD }}
