name: Build & Publish to TestPyPI

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Upload to PyPi-Test?"
        required: true
        default: "true"
        type: choice
        options:
          - "true"
          - "false"

jobs:
  build_wheels:
    # We'll build on a matrix of OSes and Python versions.
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-latest, windows-2019, windows-latest]
    env:
      CIBW_BUILD: "cp39-* cp310-* cp311-* cp312-*"
      CIBW_SDIST: "true"
      CIBW_ENVIRONMENT: "PIP_NO_CACHE_DIR=1"

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          pip install --upgrade pip && pip install cibuildwheel twine

      - name: Upgrade pip, setuptools, wheel
        run: python -m pip install --upgrade setuptools wheel

      - name: Build wheels
        run: cibuildwheel --output-dir dist

      - name: Upload to Test PyPI
        run: |
            twine upload --repository testpypi dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_PASSWORD }}
